# Generated by Django 4.1.3 on 2023-01-28 06:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheelchair_access', models.BooleanField(default=False)),
                ('audio_description', models.BooleanField(default=False)),
                ('braille', models.BooleanField(default=False)),
                ('sign_language', models.BooleanField(default=False)),
                ('closed_captioning', models.BooleanField(default=False)),
                ('tactile_path', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ThemePark',
            fields=[
                ('park_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('park_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeParkArea',
            fields=[
                ('area_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('area_name', models.CharField(max_length=255)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkRidesApp.themepark')),
            ],
        ),
        migrations.CreateModel(
            name='ThemeParkRide',
            fields=[
                ('ride_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('ride_name', models.CharField(max_length=255)),
                ('ride_description', models.TextField()),
                ('ride_thumbnail', models.ImageField(upload_to='rides_images/')),
                ('age_restriction', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('height_restriction', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('ride_type', models.CharField(max_length=255)),
                ('ride_capacity', models.PositiveIntegerField()),
                ('ride_duration', models.DurationField()),
                ('opening_hour', models.TimeField()),
                ('closing_hour', models.TimeField(default='22:00:00')),
                ('under_maintenance', models.BooleanField(default=False)),
                ('accesibility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParkRidesApp.accessibility')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkRidesApp.themepark')),
                ('ride_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkRidesApp.themeparkarea')),
            ],
        ),
    ]
