# Generated by Django 4.1.3 on 2023-01-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkRidesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themeparkride',
            name='accesibility',
        ),
        migrations.AddField(
            model_name='themeparkride',
            name='accessibility_audio_description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themeparkride',
            name='accessibility_braille',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themeparkride',
            name='accessibility_closed_captioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themeparkride',
            name='accessibility_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themeparkride',
            name='accessibility_sign_language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themeparkride',
            name='accessibility_tactile_path',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themeparkride',
            name='accessibility_wheelchair_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='themepark',
            name='park_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='themeparkarea',
            name='area_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='themeparkride',
            name='ride_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Accessibility',
        ),
    ]
